#!/usr/bin/env node
// Copies runtime assets (WASM codecs, ONNX Runtime) from temporarily installed
// npm packages into the repo, then regenerates VENDOR.md with SHA-256 hashes.
//
// Run manually, only when deliberately upgrading a vendored asset:
//   node scripts/vendor.mjs
//
// Nothing here runs during `npm run build`; the build uses the committed files.

import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// Hand-written type declarations for the Emscripten glue modules. The upstream
// .d.ts files reference a global EmscriptenWasm namespace we don't vendor.
const emscriptenDts = (encodeSignature) => `// Generated by scripts/vendor.mjs
export type EncoderModule = {
  encode: ${encodeSignature};
};
declare const moduleFactory: (options?: Record<string, unknown>) => Promise<EncoderModule>;
export default moduleFactory;
`;

const jsquashEncodeSignature =
  '(data: Uint8Array | Uint8ClampedArray, width: number, height: number, options: Record<string, unknown>) => Uint8Array | null';

const oxipngDts = `// Generated by scripts/vendor.mjs
export function optimise(data: Uint8Array, level: number, interlace: boolean, optimizeAlpha: boolean): Uint8Array;
declare const init: (moduleOrPath?: RequestInfo | URL | Response | BufferSource | WebAssembly.Module) => Promise<unknown>;
export default init;
`;

/**
 * @typedef {{ from: string; to?: string; dts?: string }} FileSpec
 * @typedef {{ name: string; version: string; license: string; url: string; dest: string; files: FileSpec[] }} PackageSpec
 */

/** @type {PackageSpec[]} */
const packages = [
  {
    name: '@jsquash/jpeg',
    version: '1.6.0',
    license: 'Apache-2.0 (wrapper); MozJPEG: IJG + BSD-3-Clause + zlib',
    url: 'https://github.com/jamsinclair/jSquash/tree/main/packages/jpeg',
    dest: 'src/vendor/jsquash/jpeg@1.6.0',
    files: [
      { from: 'codec/enc/mozjpeg_enc.js', dts: emscriptenDts(jsquashEncodeSignature) },
      { from: 'codec/enc/mozjpeg_enc.wasm' },
      { from: 'LICENSE' },
      { from: 'codec/LICENSE.codec.md' },
    ],
  },
  {
    name: '@jsquash/webp',
    version: '1.5.0',
    license: 'Apache-2.0 (wrapper); libwebp: BSD-3-Clause',
    url: 'https://github.com/jamsinclair/jSquash/tree/main/packages/webp',
    dest: 'src/vendor/jsquash/webp@1.5.0',
    files: [
      { from: 'codec/enc/webp_enc.js', dts: emscriptenDts(jsquashEncodeSignature) },
      { from: 'codec/enc/webp_enc.wasm' },
      { from: 'codec/enc/webp_enc_simd.js', dts: emscriptenDts(jsquashEncodeSignature) },
      { from: 'codec/enc/webp_enc_simd.wasm' },
      { from: 'LICENSE' },
      { from: 'codec/LICENSE.codec.md' },
    ],
  },
  {
    name: '@jsquash/avif',
    version: '2.1.1',
    license: 'Apache-2.0 (wrapper); libavif: BSD-2-Clause; libaom: BSD-2-Clause + AOM patent license',
    url: 'https://github.com/jamsinclair/jSquash/tree/main/packages/avif',
    dest: 'src/vendor/jsquash/avif@2.1.1',
    files: [
      { from: 'codec/enc/avif_enc.js', dts: emscriptenDts(jsquashEncodeSignature) },
      { from: 'codec/enc/avif_enc.wasm' },
      { from: 'LICENSE' },
    ],
  },
  {
    name: '@jsquash/oxipng',
    version: '2.3.0',
    license: 'Apache-2.0 (wrapper); oxipng: MIT',
    url: 'https://github.com/jamsinclair/jSquash/tree/main/packages/oxipng',
    dest: 'src/vendor/jsquash/oxipng@2.3.0',
    files: [
      { from: 'codec/pkg/squoosh_oxipng.js', dts: oxipngDts },
      { from: 'codec/pkg/squoosh_oxipng_bg.wasm' },
      { from: 'LICENSE' },
      { from: 'codec/LICENSE.codec.md' },
    ],
  },
];

const sha256 = (path) => createHash('sha256').update(readFileSync(path)).digest('hex');

const listFiles = (dir) =>
  readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? listFiles(full) : [full];
  });

const vendorPackages = () => {
  const tmp = mkdtempSync(join(tmpdir(), 'localcrop-vendor-'));
  try {
    writeFileSync(join(tmp, 'package.json'), '{"private":true}');
    const specs = packages.map((p) => `${p.name}@${p.version}`).join(' ');
    console.log(`Installing ${specs} into ${tmp}`);
    execSync(`npm install --no-save --ignore-scripts --no-audit --no-fund ${specs}`, { cwd: tmp, stdio: 'inherit' });

    for (const pkg of packages) {
      const srcDir = join(tmp, 'node_modules', pkg.name);
      const destDir = join(root, pkg.dest);
      rmSync(destDir, { recursive: true, force: true });
      mkdirSync(destDir, { recursive: true });
      for (const file of pkg.files) {
        const target = join(destDir, file.to ?? file.from.split('/').pop());
        cpSync(join(srcDir, file.from), target);
        if (file.dts) writeFileSync(target.replace(/\.js$/, '.d.ts'), file.dts);
      }
      console.log(`Vendored ${pkg.name}@${pkg.version} → ${pkg.dest}`);
    }
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
};

const renderVendorMd = () => {
  const sections = packages.map((pkg) => {
    const destDir = join(root, pkg.dest);
    const rows = listFiles(destDir)
      .map((file) => `| \`${relative(destDir, file).split(sep).join('/')}\` | ${statSync(file).size} | \`${sha256(file)}\` |`)
      .join('\n');
    return `### ${pkg.name}@${pkg.version}

- **Source package:** \`${pkg.name}\` (npm)
- **Exact version:** ${pkg.version}
- **License:** ${pkg.license}
- **Source URL:** ${pkg.url}
- **Location:** \`${pkg.dest}/\`

| File | Bytes | SHA-256 |
|---|---:|---|
${rows}
`;
  });

  const manualPath = join(root, 'scripts', 'vendor-manual.md');
  const manual = existsSync(manualPath) ? `\n${readFileSync(manualPath, 'utf8')}` : '';

  return `# Vendored runtime assets

Generated by \`node scripts/vendor.mjs\`. Do not edit by hand; edit the script
(or \`scripts/vendor-manual.md\` for assets not sourced from npm) and re-run it.

These files are committed so that a rebuild months from now produces the same
app, with no runtime or build-time network access to package registries or CDNs.

Only the **single-threaded encoder** builds are vendored: GitHub Pages can't send
COOP/COEP headers, so \`SharedArrayBuffer\` (and therefore WASM threads) is unavailable.
The jSquash JS wrappers are *not* vendored — they pull in \`wasm-feature-detect\` and
multi-thread code paths. \`src/worker/codecs.ts\` drives the Emscripten glue directly,
using the same default options as the upstream wrappers.

${sections.join('\n')}${manual}`;
};

const main = () => {
  const onlyDocs = process.argv.includes('--docs-only');
  if (!onlyDocs) vendorPackages();
  writeFileSync(join(root, 'VENDOR.md'), renderVendorMd());
  console.log('Wrote VENDOR.md');
};

main();
